version: '3.7'
services:
  api:
    build: .
    image: final-api
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mongodb-1
      - redis
    links:
      - redis
    # networks:
    #   - redis-net
    environment:
      MONGO_DATABASE: ${MONGO_DB_NAME}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongodb-1
      MONGO_PORT: 27017
      MONGO_REPL_SET_NAME: ${MONGO_REPL_SET_NAME}
      REDIS_HOST: redis

  mongodb-1:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    restart: always
    volumes:
      - mongo-data1:/data/db
      - ./lib/dump:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    command: --keyFile /data/mongodb-keyfile --replSet ${MONGO_REPL_SET_NAME}

  mongodb-2:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    restart: always
    volumes:
      - mongo-data2:/data/db
      - ./lib/dump:/docker-entrypoint-initdb.d
      - ./mongodb-keyfile:/data/mongodb-keyfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    command: --keyFile /data/mongodb-keyfile --replSet ${MONGO_REPL_SET_NAME}

  mongodb-3:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    restart: always
    volumes:
      - mongo-data3:/data/db
      - ./lib/dump:/docker-entrypoint-initdb.d
      - ./mongodb-keyfile:/data/mongodb-keyfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    command: --keyFile /data/mongodb-keyfile --replSet ${MONGO_REPL_SET_NAME}

  mongodb-repl-set-init:
    image: mongo:latest
    volumes:
      - ./rs-init:/rs-init/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_REPL_SET_NAME: ${MONGO_REPL_SET_NAME}
      MONGO_REPL_SET_HOSTS: mongodb-1 mongodb-2 mongodb-3
    entrypoint: sh /rs-init/rs-init.sh

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    expose:
      - 6379
    # networks:
    #   - redis-net
    restart: always

# networks:
#   redis-net:

volumes:
  mongo-data1:
    name: tarpaulin-university-data1
  mongo-data2:
    name: tarpaulin-university-data2
  mongo-data3:
    name: tarpaulin-university-data3
