version: '3.7'
services:
  api:
    build: .
    image: final-api
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mongodb
      - redis
    links:
      - redis
    # networks:
    #   - redis-net
    environment:
      MONGO_DATABASE: ${MONGO_DB_NAME}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      REDIS_HOST: redis

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
      - ./lib/dump:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    expose:
      - 6379
    # networks:
    #   - redis-net
    restart: always

# networks:
#   redis-net:

volumes:
  mongo-data:
    name: tarpaulin-university-data
